### ISSUE TITLE
Why ROS2 can not find the python module?

### ISSUE THREAD

**Issue by is3rlab** [abizovnuralem/go2_ros2_sdk#98]
Hello，

I installed the package in the Pycharm Conda environment. However, when I launch the go2_robot_sdk robot.launch.py, I can not the python modules such as "aiortc", "open3d", correctly. I try several methods to set the path, it did not work. Please check more details as below:

IP list: ['']
[INFO] [robot_state_publisher-1]: process started with pid [54100]
[INFO] [pointcloud_to_laserscan_node-2]: process started with pid [54102]
[INFO] [go2_driver_node-3]: process started with pid [54104]
[INFO] [lidar_to_pointcloud-4]: process started with pid [54106]
[INFO] [rviz2-5]: process started with pid [54108]
[INFO] [joy_node-6]: process started with pid [54110]
[INFO] [teleop_node-7]: process started with pid [54112]
[INFO] [twist_mux-8]: process started with pid [54114]
[INFO] [foxglove_bridge-9]: process started with pid [54116]
[INFO] [async_slam_toolbox_node-10]: process started with pid [54118]
[INFO] [controller_server-11]: process started with pid [54120]
[INFO] [smoother_server-12]: process started with pid [54122]
[INFO] [planner_server-13]: process started with pid [54124]
[INFO] [behavior_server-14]: process started with pid [54126]
[INFO] [bt_navigator-15]: process started with pid [54128]
[INFO] [waypoint_follower-16]: process started with pid [54130]
[INFO] [velocity_smoother-17]: process started with pid [54132]
[INFO] [lifecycle_manager-18]: process started with pid [54134]
[teleop_node-7] [INFO] [1729619790.437410666] [TeleopTwistJoy]: Linear axis x on 1 at scale 0.200000.
[teleop_node-7] [INFO] [1729619790.437467305] [TeleopTwistJoy]: Linear axis y on 3 at scale 0.200000.
[teleop_node-7] [INFO] [1729619790.437472416] [TeleopTwistJoy]: Angular axis yaw on 6 at scale 0.200000.
[twist_mux-8] [INFO] [1729619790.438412433] [twist_mux]: Topic handler 'topics.joy' subscribed to topic 'cmd_vel_joy': timeout = 0.500000s , priority = 10.
[twist_mux-8] [INFO] [1729619790.440085606] [twist_mux]: Topic handler 'topics.navigation' subscribed to topic 'cmd_vel': timeout = 0.500000s , priority = 5.
[velocity_smoother-17] [INFO] [1729619790.444324242] [velocity_smoother]: 
[velocity_smoother-17]  velocity_smoother lifecycle node launched. 
[velocity_smoother-17]  Waiting on external lifecycle transitions to activate
[velocity_smoother-17]  See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-11] [INFO] [1729619790.444678831] [controller_server]: 
[controller_server-11]  controller_server lifecycle node launched. 
[controller_server-11]  Waiting on external lifecycle transitions to activate
[controller_server-11]  See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-11] [INFO] [1729619790.448720210] [controller_server]: Creating controller server
[robot_state_publisher-1] [INFO] [1729619790.449064340] [robot_state_publisher]: got segment FL_calf
[robot_state_publisher-1] [INFO] [1729619790.449157803] [robot_state_publisher]: got segment FL_calflower
[robot_state_publisher-1] [INFO] [1729619790.449170851] [robot_state_publisher]: got segment FL_calflower1
[robot_state_publisher-1] [INFO] [1729619790.449178619] [robot_state_publisher]: got segment FL_foot
[robot_state_publisher-1] [INFO] [1729619790.449185533] [robot_state_publisher]: got segment FL_hip
[robot_state_publisher-1] [INFO] [1729619790.449192125] [robot_state_publisher]: got segment FL_thigh
[robot_state_publisher-1] [INFO] [1729619790.449198504] [robot_state_publisher]: got segment FR_calf
[robot_state_publisher-1] [INFO] [1729619790.449204931] [robot_state_publisher]: got segment FR_calflower
[robot_state_publisher-1] [INFO] [1729619790.449211702] [robot_state_publisher]: got segment FR_calflower1
[robot_state_publisher-1] [INFO] [1729619790.449218105] [robot_state_publisher]: got segment FR_foot
[robot_state_publisher-1] [INFO] [1729619790.449224603] [robot_state_publisher]: got segment FR_hip
[robot_state_publisher-1] [INFO] [1729619790.449230942] [robot_state_publisher]: got segment FR_thigh
[robot_state_publisher-1] [INFO] [1729619790.449237343] [robot_state_publisher]: got segment Head_lower
[robot_state_publisher-1] [INFO] [1729619790.449243654] [robot_state_publisher]: got segment Head_upper
[robot_state_publisher-1] [INFO] [1729619790.449249801] [robot_state_publisher]: got segment RL_calf
[robot_state_publisher-1] [INFO] [1729619790.449256068] [robot_state_publisher]: got segment RL_calflower
[robot_state_publisher-1] [INFO] [1729619790.449262603] [robot_state_publisher]: got segment RL_calflower1
[robot_state_publisher-1] [INFO] [1729619790.449269096] [robot_state_publisher]: got segment RL_foot
[robot_state_publisher-1] [INFO] [1729619790.449275451] [robot_state_publisher]: got segment RL_hip
[robot_state_publisher-1] [INFO] [1729619790.449282287] [robot_state_publisher]: got segment RL_thigh
[robot_state_publisher-1] [INFO] [1729619790.449288903] [robot_state_publisher]: got segment RR_calf
[robot_state_publisher-1] [INFO] [1729619790.449295350] [robot_state_publisher]: got segment RR_calflower
[robot_state_publisher-1] [INFO] [1729619790.449301918] [robot_state_publisher]: got segment RR_calflower1
[robot_state_publisher-1] [INFO] [1729619790.449308386] [robot_state_publisher]: got segment RR_foot
[robot_state_publisher-1] [INFO] [1729619790.449314797] [robot_state_publisher]: got segment RR_hip
[robot_state_publisher-1] [INFO] [1729619790.449321495] [robot_state_publisher]: got segment RR_thigh
[robot_state_publisher-1] [INFO] [1729619790.449327996] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-1] [INFO] [1729619790.449334612] [robot_state_publisher]: got segment base_link
[robot_state_publisher-1] [INFO] [1729619790.449341157] [robot_state_publisher]: got segment front_camera
[robot_state_publisher-1] [INFO] [1729619790.449347678] [robot_state_publisher]: got segment imu
[robot_state_publisher-1] [INFO] [1729619790.449354427] [robot_state_publisher]: got segment map
[robot_state_publisher-1] [INFO] [1729619790.449361185] [robot_state_publisher]: got segment odom
[robot_state_publisher-1] [INFO] [1729619790.449367759] [robot_state_publisher]: got segment radar
[smoother_server-12] [INFO] [1729619790.450204651] [smoother_server]: 
[smoother_server-12]    smoother_server lifecycle node launched. 
[smoother_server-12]    Waiting on external lifecycle transitions to activate
[smoother_server-12]    See https://design.ros2.org/articles/node_lifecycle.html for more information.
[smoother_server-12] [INFO] [1729619790.451020604] [smoother_server]: Creating smoother server
[bt_navigator-15] [INFO] [1729619790.450353190] [bt_navigator]: 
[bt_navigator-15]       bt_navigator lifecycle node launched. 
[bt_navigator-15]       Waiting on external lifecycle transitions to activate
[bt_navigator-15]       See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-15] [INFO] [1729619790.450449655] [bt_navigator]: Creating
[behavior_server-14] [INFO] [1729619790.452344083] [behavior_server]: 
[behavior_server-14]    behavior_server lifecycle node launched. 
[behavior_server-14]    Waiting on external lifecycle transitions to activate
[behavior_server-14]    See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-16] [INFO] [1729619790.453835087] [waypoint_follower]: 
[waypoint_follower-16]  waypoint_follower lifecycle node launched. 
[waypoint_follower-16]  Waiting on external lifecycle transitions to activate
[waypoint_follower-16]  See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-16] [INFO] [1729619790.454169840] [waypoint_follower]: Creating
[planner_server-13] [INFO] [1729619790.458245191] [planner_server]: 
[planner_server-13]     planner_server lifecycle node launched. 
[planner_server-13]     Waiting on external lifecycle transitions to activate
[planner_server-13]     See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-13] [INFO] [1729619790.459168414] [planner_server]: Creating
[async_slam_toolbox_node-10] [INFO] [1729619790.465421405] [slam_toolbox]: Node using stack size 40000000
[foxglove_bridge-9] [INFO] [1729619790.467585775] [foxglove_bridge_component_manager]: Load Library: /opt/ros/humble/lib/libfoxglove_bridge_component.so
[lifecycle_manager-18] [INFO] [1729619790.469656235] [lifecycle_manager_navigation]: Creating
[planner_server-13] [INFO] [1729619790.471452315] [global_costmap.global_costmap]: 
[planner_server-13]     global_costmap lifecycle node launched. 
[planner_server-13]     Waiting on external lifecycle transitions to activate
[planner_server-13]     See https://design.ros2.org/articles/node_lifecycle.html for more information.
[lifecycle_manager-18] [INFO] [1729619790.471454123] [lifecycle_manager_navigation]: Creating and initializing lifecycle service clients
[planner_server-13] [INFO] [1729619790.471859402] [global_costmap.global_costmap]: Creating Costmap
[foxglove_bridge-9] [INFO] [1729619790.472906241] [foxglove_bridge_component_manager]: Found class: rclcpp_components::NodeFactoryTemplate<foxglove_bridge::FoxgloveBridge>
[foxglove_bridge-9] [INFO] [1729619790.472937648] [foxglove_bridge_component_manager]: Instantiate class: rclcpp_components::NodeFactoryTemplate<foxglove_bridge::FoxgloveBridge>
[controller_server-11] [INFO] [1729619790.473042717] [local_costmap.local_costmap]: 
[controller_server-11]  local_costmap lifecycle node launched. 
[controller_server-11]  Waiting on external lifecycle transitions to activate
[controller_server-11]  See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-11] [INFO] [1729619790.473865890] [local_costmap.local_costmap]: Creating Costmap
[foxglove_bridge-9] [INFO] [1729619790.485745984] [foxglove_bridge]: Starting foxglove_bridge (humble, 0.8.0@) with WebSocket++/0.8.2
[foxglove_bridge-9] [INFO] [1729619790.486886323] [foxglove_bridge]: [WS] Server running without TLS
[lifecycle_manager-18] [INFO] [1729619790.487186267] [lifecycle_manager_navigation]: Starting managed nodes bringup...
[lifecycle_manager-18] [INFO] [1729619790.487215889] [lifecycle_manager_navigation]: Configuring controller_server
[foxglove_bridge-9] [INFO] [1729619790.487365864] [foxglove_bridge]: [WS] WebSocket server listening at ws://0.0.0.0:8765
[foxglove_bridge-9] [INFO] [1729619790.487371030] [foxglove_bridge]: [WS] WebSocket server run loop started
[controller_server-11] [INFO] [1729619790.489087685] [controller_server]: Configuring controller interface
[controller_server-11] [INFO] [1729619790.489308713] [controller_server]: getting goal checker plugins..
[controller_server-11] [INFO] [1729619790.490742204] [controller_server]: Controller frequency set to 3.0000Hz
[controller_server-11] [INFO] [1729619790.490790554] [local_costmap.local_costmap]: Configuring
[pointcloud_to_laserscan_node-2] [INFO] [1729619790.491600092] [pointcloud_to_laserscan]: Got a subscriber to laserscan, starting pointcloud subscriber
[async_slam_toolbox_node-10] [INFO] [1729619790.494220367] [slam_toolbox]: Using solver plugin solver_plugins::CeresSolver
[async_slam_toolbox_node-10] [INFO] [1729619790.494490972] [slam_toolbox]: CeresSolver: Using SCHUR_JACOBI preconditioner.
[controller_server-11] [INFO] [1729619790.496141044] [local_costmap.local_costmap]: Using plugin "static_layer"
[controller_server-11] [INFO] [1729619790.498932737] [local_costmap.local_costmap]: Subscribing to the map topic (/map) with transient local durability
[controller_server-11] [INFO] [1729619790.499924071] [local_costmap.local_costmap]: Initialized plugin "static_layer"
[controller_server-11] [INFO] [1729619790.499949637] [local_costmap.local_costmap]: Using plugin "voxel_layer"
[controller_server-11] [INFO] [1729619790.500508889] [local_costmap.local_costmap]: Subscribed to Topics: scan
[controller_server-11] [INFO] [1729619790.503783651] [local_costmap.local_costmap]: Initialized plugin "voxel_layer"
[controller_server-11] [INFO] [1729619790.503809879] [local_costmap.local_costmap]: Using plugin "inflation_layer"
[controller_server-11] [INFO] [1729619790.504077140] [local_costmap.local_costmap]: Initialized plugin "inflation_layer"
[controller_server-11] [ERROR] [1729619790.506094175] [local_costmap.local_costmap]: The configured inflation radius (0.100) is smaller than the computed inscribed radius (0.210) of your footprint, it is highly recommended to set inflation radius to be at least as big as the inscribed radius to avoid collisions
[controller_server-11] [INFO] [1729619790.507502616] [controller_server]: Created progress_checker : progress_checker of type nav2_controller::SimpleProgressChecker
[controller_server-11] [INFO] [1729619790.507916219] [controller_server]: Created goal checker : general_goal_checker of type nav2_controller::SimpleGoalChecker
[controller_server-11] [INFO] [1729619790.508052816] [controller_server]: Controller Server has general_goal_checker  goal checkers available.
[controller_server-11] [INFO] [1729619790.508825383] [controller_server]: Created controller : FollowPath of type dwb_core::DWBLocalPlanner
[controller_server-11] [INFO] [1729619790.509387553] [controller_server]: Setting transform_tolerance to 0.200000
[controller_server-11] [INFO] [1729619790.515369078] [controller_server]: Using critic "RotateToGoal" (dwb_critics::RotateToGoalCritic)
[controller_server-11] [INFO] [1729619790.515747484] [controller_server]: Critic plugin initialized
[controller_server-11] [INFO] [1729619790.515837650] [controller_server]: Using critic "Oscillation" (dwb_critics::OscillationCritic)
[controller_server-11] [INFO] [1729619790.516207006] [controller_server]: Critic plugin initialized
[controller_server-11] [INFO] [1729619790.516309683] [controller_server]: Using critic "BaseObstacle" (dwb_critics::BaseObstacleCritic)
[controller_server-11] [INFO] [1729619790.516409832] [controller_server]: Critic plugin initialized
[controller_server-11] [INFO] [1729619790.516469158] [controller_server]: Using critic "GoalAlign" (dwb_critics::GoalAlignCritic)
[controller_server-11] [INFO] [1729619790.516665084] [controller_server]: Critic plugin initialized
[controller_server-11] [INFO] [1729619790.516722179] [controller_server]: Using critic "PathAlign" (dwb_critics::PathAlignCritic)
[controller_server-11] [INFO] [1729619790.516865309] [controller_server]: Critic plugin initialized
[controller_server-11] [INFO] [1729619790.516918174] [controller_server]: Using critic "PathDist" (dwb_critics::PathDistCritic)
[controller_server-11] [INFO] [1729619790.517034195] [controller_server]: Critic plugin initialized
[controller_server-11] [INFO] [1729619790.517080202] [controller_server]: Using critic "GoalDist" (dwb_critics::GoalDistCritic)
[controller_server-11] [INFO] [1729619790.517169102] [controller_server]: Critic plugin initialized
[controller_server-11] [INFO] [1729619790.517179307] [controller_server]: Controller Server has FollowPath  controllers available.
[lifecycle_manager-18] [INFO] [1729619790.520758497] [lifecycle_manager_navigation]: Configuring smoother_server
[smoother_server-12] [INFO] [1729619790.520873165] [smoother_server]: Configuring smoother server
[go2_driver_node-3] Traceback (most recent call last):
[go2_driver_node-3]   File "/home/rick/Documents/Projects/go2_ros2_sdk/ros2_ws/install/go2_robot_sdk/lib/go2_robot_sdk/go2_driver_node", line 33, in <module>
[go2_driver_node-3]     sys.exit(load_entry_point('go2-robot-sdk==0.0.0', 'console_scripts', 'go2_driver_node')())
[go2_driver_node-3]   File "/home/rick/Documents/Projects/go2_ros2_sdk/ros2_ws/install/go2_robot_sdk/lib/go2_robot_sdk/go2_driver_node", line 25, in importlib_load_entry_point
[go2_driver_node-3]     return next(matches).load()
[go2_driver_node-3]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[go2_driver_node-3]     module = import_module(match.group('module'))
[go2_driver_node-3]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[go2_driver_node-3]     return _bootstrap._gcd_import(name[level:], package, level)
[go2_driver_node-3]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[go2_driver_node-3]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[go2_driver_node-3]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[go2_driver_node-3]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[go2_driver_node-3]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[go2_driver_node-3]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[go2_driver_node-3]   File "/home/rick/Documents/Projects/go2_ros2_sdk/ros2_ws/install/go2_robot_sdk/lib/python3.10/site-packages/go2_robot_sdk/go2_driver_node.py", line 31, in <module>
**[go2_driver_node-3]     from aiortc import MediaStreamTrack
[go2_driver_node-3] ModuleNotFoundError: No module named 'aiortc'**
[smoother_server-12] [INFO] [1729619790.525057763] [smoother_server]: Created smoother : simple_smoother of type nav2_smoother::SimpleSmoother
[smoother_server-12] [INFO] [1729619790.525363818] [smoother_server]: Smoother Server has simple_smoother  smoothers available.
[lifecycle_manager-18] [INFO] [1729619790.528693343] [lifecycle_manager_navigation]: Configuring planner_server
[planner_server-13] [INFO] [1729619790.528915956] [planner_server]: Configuring
[planner_server-13] [INFO] [1729619790.528952188] [global_costmap.global_costmap]: Configuring
[ERROR] [go2_driver_node-3]: process has died [pid 54104, exit code 1, cmd '/home/rick/Documents/Projects/go2_ros2_sdk/ros2_ws/install/go2_robot_sdk/lib/go2_robot_sdk/go2_driver_node --ros-args --params-file /tmp/launch_params_m26zp5d8'].
[planner_server-13] [INFO] [1729619790.586230270] [global_costmap.global_costmap]: Using plugin "static_layer"
[planner_server-13] [INFO] [1729619790.587985677] [global_costmap.global_costmap]: Subscribing to the map topic (/map) with transient local durability
[planner_server-13] [INFO] [1729619790.588702909] [global_costmap.global_costmap]: Initialized plugin "static_layer"
[planner_server-13] [INFO] [1729619790.588721681] [global_costmap.global_costmap]: Using plugin "voxel_layer"
[planner_server-13] [INFO] [1729619790.589034593] [global_costmap.global_costmap]: Subscribed to Topics: scan
[lidar_to_pointcloud-4] Traceback (most recent call last):
[lidar_to_pointcloud-4]   File "/home/rick/Documents/Projects/go2_ros2_sdk/ros2_ws/install/go2_robot_sdk/lib/go2_robot_sdk/lidar_to_pointcloud", line 33, in <module>
[lidar_to_pointcloud-4]     sys.exit(load_entry_point('go2-robot-sdk==0.0.0', 'console_scripts', 'lidar_to_pointcloud')())
[lidar_to_pointcloud-4]   File "/home/rick/Documents/Projects/go2_ros2_sdk/ros2_ws/install/go2_robot_sdk/lib/go2_robot_sdk/lidar_to_pointcloud", line 25, in importlib_load_entry_point
[lidar_to_pointcloud-4]     return next(matches).load()
[lidar_to_pointcloud-4]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[lidar_to_pointcloud-4]     module = import_module(match.group('module'))
[lidar_to_pointcloud-4]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[lidar_to_pointcloud-4]     return _bootstrap._gcd_import(name[level:], package, level)
[lidar_to_pointcloud-4]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[lidar_to_pointcloud-4]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[lidar_to_pointcloud-4]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[lidar_to_pointcloud-4]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[lidar_to_pointcloud-4]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[lidar_to_pointcloud-4]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[lidar_to_pointcloud-4]   File "/home/rick/Documents/Projects/go2_ros2_sdk/ros2_ws/install/go2_robot_sdk/lib/python3.10/site-packages/go2_robot_sdk/lidar_to_point.py", line 30, in <module>
**[lidar_to_pointcloud-4]     import open3d as o3d
[lidar_to_pointcloud-4] ModuleNotFoundError: No module named 'open3d'**
[ERROR] [lidar_to_pointcloud-4]: process has died [pid 54106, exit code 1, cmd '/home/rick/Documents/Projects/go2_ros2_sdk/ros2_ws/install/go2_robot_sdk/lib/go2_robot_sdk/lidar_to_pointcloud --ros-args --params-file /tmp/launch_params_boy639yq'].
[planner_server-13] [INFO] [1729619790.772209224] [global_costmap.global_costmap]: Initialized plugin "voxel_layer"
[planner_server-13] [INFO] [1729619790.772242553] [global_costmap.global_costmap]: Using plugin "inflation_layer"
[planner_server-13] [INFO] [1729619790.775598577] [global_costmap.global_costmap]: Initialized plugin "inflation_layer"
[planner_server-13] [ERROR] [1729619790.777796710] [global_costmap.global_costmap]: The configured inflation radius (0.100) is smaller than the computed inscribed radius (0.210) of your footprint, it is highly recommended to set inflation radius to be at least as big as the inscribed radius to avoid collisions
[planner_server-13] [INFO] [1729619790.778974877] [planner_server]: Created global planner plugin GridBased of type nav2_navfn_planner/NavfnPlanner
[planner_server-13] [INFO] [1729619790.778992034] [planner_server]: Configuring plugin GridBased of type NavfnPlanner
[planner_server-13] [INFO] [1729619790.828589107] [planner_server]: Planner Server has GridBased  planners available.
[lifecycle_manager-18] [INFO] [1729619790.832688406] [lifecycle_manager_navigation]: Configuring behavior_server
[behavior_server-14] [INFO] [1729619790.832862190] [behavior_server]: Configuring
[behavior_server-14] [INFO] [1729619790.836767557] [behavior_server]: Creating behavior plugin spin of type nav2_behaviors/Spin
[behavior_server-14] [INFO] [1729619790.837176622] [behavior_server]: Configuring spin
[behavior_server-14] [INFO] [1729619790.839349952] [behavior_server]: Creating behavior plugin backup of type nav2_behaviors/BackUp
[behavior_server-14] [INFO] [1729619790.839738806] [behavior_server]: Configuring backup
[behavior_server-14] [INFO] [1729619790.841281559] [behavior_server]: Creating behavior plugin drive_on_heading of type nav2_behaviors/DriveOnHeading
[behavior_server-14] [INFO] [1729619790.841659091] [behavior_server]: Configuring drive_on_heading
[behavior_server-14] [INFO] [1729619790.843577086] [behavior_server]: Creating behavior plugin assisted_teleop of type nav2_behaviors/AssistedTeleop
[behavior_server-14] [INFO] [1729619790.844450966] [behavior_server]: Configuring assisted_teleop
[behavior_server-14] [INFO] [1729619790.846755479] [behavior_server]: Creating behavior plugin wait of type nav2_behaviors/Wait
[behavior_server-14] [INFO] [1729619790.847128086] [behavior_server]: Configuring wait
[lifecycle_manager-18] [INFO] [1729619790.848932709] [lifecycle_manager_navigation]: Configuring bt_navigator
[bt_navigator-15] [INFO] [1729619790.849055812] [bt_navigator]: Configuring
[lifecycle_manager-18] [INFO] [1729619790.878119556] [lifecycle_manager_navigation]: Configuring waypoint_follower
[waypoint_follower-16] [INFO] [1729619790.878231933] [waypoint_follower]: Configuring
[waypoint_follower-16] [INFO] [1729619790.882821549] [waypoint_follower]: Created waypoint_task_executor : wait_at_waypoint of type nav2_waypoint_follower::WaitAtWaypoint
[lifecycle_manager-18] [INFO] [1729619790.883152232] [lifecycle_manager_navigation]: Configuring velocity_smoother
[velocity_smoother-17] [INFO] [1729619790.883277475] [velocity_smoother]: Configuring velocity smoother
[lifecycle_manager-18] [INFO] [1729619790.885134982] [lifecycle_manager_navigation]: Activating controller_server
[controller_server-11] [INFO] [1729619790.885242249] [controller_server]: Activating
[controller_server-11] [INFO] [1729619790.885285112] [local_costmap.local_costmap]: Activating
[controller_server-11] [INFO] [1729619790.885333220] [local_costmap.local_costmap]: Checking transform
[controller_server-11] [INFO] [1729619790.885445431] [local_costmap.local_costmap]: start
[rviz2-5] [INFO] [1729619791.003212193] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-5] [INFO] [1729619791.003321369] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-5] [INFO] [1729619791.025309157] [rviz2]: Stereo is NOT SUPPORTED
[pointcloud_to_laserscan_node-2] [WARN] [1729619791.090028966] [pointcloud_to_laserscan]: New subscription discovered on topic '/scan', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
[rviz2-5] [WARN] [1729619791.109907052] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-5] [WARN] [1729619791.119024394] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-5] [ERROR] [1729619791.408004110] [rviz2]: The link is static or has unrealistic inertia, so the equivalent inertia box will not be shown.
[rviz2-5] 
[rviz2-5] [ERROR] [1729619791.408094765] [rviz2]: The link is static or has unrealistic inertia, so the equivalent inertia box will not be shown.
[rviz2-5] 
[rviz2-5] [INFO] [1729619791.459603389] [rviz2]: Stereo is NOT SUPPORTED
[controller_server-11] [INFO] [1729619791.936034714] [controller_server]: Creating bond (controller_server) to lifecycle manager.
[lifecycle_manager-18] [INFO] [1729619792.039663868] [lifecycle_manager_navigation]: Server controller_server connected with bond.
[lifecycle_manager-18] [INFO] [1729619792.039727101] [lifecycle_manager_navigation]: Activating smoother_server
[smoother_server-12] [INFO] [1729619792.040091346] [smoother_server]: Activating
[smoother_server-12] [INFO] [1729619792.040136397] [smoother_server]: Creating bond (smoother_server) to lifecycle manager.
[lifecycle_manager-18] [INFO] [1729619792.148755860] [lifecycle_manager_navigation]: Server smoother_server connected with bond.
[lifecycle_manager-18] [INFO] [1729619792.148830496] [lifecycle_manager_navigation]: Activating planner_server
[planner_server-13] [INFO] [1729619792.149297334] [planner_server]: Activating
[planner_server-13] [INFO] [1729619792.149366341] [global_costmap.global_costmap]: Activating
[planner_server-13] [INFO] [1729619792.149390662] [global_costmap.global_costmap]: Checking transform
[planner_server-13] [INFO] [1729619792.149549493] [global_costmap.global_costmap]: start
[planner_server-13] [INFO] [1729619793.550572717] [planner_server]: Activating plugin GridBased of type NavfnPlanner
[planner_server-13] [INFO] [1729619793.551810615] [planner_server]: Creating bond (planner_server) to lifecycle manager.
[lifecycle_manager-18] [INFO] [1729619793.654527086] [lifecycle_manager_navigation]: Server planner_server connected with bond.
[lifecycle_manager-18] [INFO] [1729619793.654606511] [lifecycle_manager_navigation]: Activating behavior_server
[behavior_server-14] [INFO] [1729619793.655119846] [behavior_server]: Activating
[behavior_server-14] [INFO] [1729619793.655142726] [behavior_server]: Activating spin
[behavior_server-14] [INFO] [1729619793.655151120] [behavior_server]: Activating backup
[behavior_server-14] [INFO] [1729619793.655156968] [behavior_server]: Activating drive_on_heading
[behavior_server-14] [INFO] [1729619793.655161905] [behavior_server]: Activating assisted_teleop
[behavior_server-14] [INFO] [1729619793.655166606] [behavior_server]: Activating wait
[behavior_server-14] [INFO] [1729619793.655175478] [behavior_server]: Creating bond (behavior_server) to lifecycle manager.
[lifecycle_manager-18] [INFO] [1729619793.757910077] [lifecycle_manager_navigation]: Server behavior_server connected with bond.
[lifecycle_manager-18] [INFO] [1729619793.757969643] [lifecycle_manager_navigation]: Activating bt_navigator
[bt_navigator-15] [INFO] [1729619793.758462935] [bt_navigator]: Activating
[bt_navigator-15] [INFO] [1729619793.792520815] [bt_navigator]: Creating bond (bt_navigator) to lifecycle manager.
[lifecycle_manager-18] [INFO] [1729619793.895822025] [lifecycle_manager_navigation]: Server bt_navigator connected with bond.
[lifecycle_manager-18] [INFO] [1729619793.895901293] [lifecycle_manager_navigation]: Activating waypoint_follower
[waypoint_follower-16] [INFO] [1729619793.896287416] [waypoint_follower]: Activating
[waypoint_follower-16] [INFO] [1729619793.896334483] [waypoint_follower]: Creating bond (waypoint_follower) to lifecycle manager.
[lifecycle_manager-18] [INFO] [1729619794.001139954] [lifecycle_manager_navigation]: Server waypoint_follower connected with bond.
[lifecycle_manager-18] [INFO] [1729619794.001204813] [lifecycle_manager_navigation]: Activating velocity_smoother
[velocity_smoother-17] [INFO] [1729619794.001466715] [velocity_smoother]: Activating
[velocity_smoother-17] [INFO] [1729619794.001517667] [velocity_smoother]: Creating bond (velocity_smoother) to lifecycle manager.
[lifecycle_manager-18] [INFO] [1729619794.107740008] [lifecycle_manager_navigation]: Server velocity_smoother connected with bond.
[lifecycle_manager-18] [INFO] [1729619794.107904238] [lifecycle_manager_navigation]: Managed nodes are active
[lifecycle_manager-18] [INFO] [1729619794.107973019] [lifecycle_manager_navigation]: Creating bond timer...
[controller_server-11] [WARN] [1729619800.885751996] [local_costmap.local_costmap]: Can't update static costmap layer, no map received
[planner_server-13] [WARN] [1729619802.340235826] [global_costmap.global_costmap]: Can't update static costmap layer, no map received
[controller_server-11] [WARN] [1729619810.885635841] [local_costmap.local_costmap]: Can't update static costmap layer, no map received
[planner_server-13] [WARN] [1729619812.318996828] [global_costmap.global_costmap]: Can't update static costmap layer, no map received
[controller_server-11] [WARN] [1729619820.885694708] [local_costmap.local_costmap]: Can't update static costmap layer, no map received
[planner_server-13] [WARN] [1729619822.324199985] [global_costmap.global_costmap]: Can't update static costmap layer, no map received

**Comment by tfoldi** [comment]
did you update the submodules recursively? `aiortc` installed/included from source

**Comment by tfoldi** [comment]
also, the `requirements.txt` in the top-level folder lists all these modules. did you install them in your conda env?

**Comment by is3rlab** [comment]
> also, the `requirements.txt` in the top-level folder lists all these modules. did you install them in your conda env?

Yes, I installed all the requirements in the conda env. However, when I run the "ros2 launch go2_robot_sdk robot.launch.py", it can not find the module.

**Comment by edugm94** [comment]
> > also, the `requirements.txt` in the top-level folder lists all these modules. did you install them in your conda env?
> 
> Yes, I installed all the requirements in the conda env. However, when I run the "ros2 launch go2_robot_sdk robot.launch.py", it can not find the module.

Hi, 

could you solve this issue?

**Comment by tfoldi** [comment]
can you show the output of the `pip list | grep aiortc` before running `ros2 launch go2_robot_sdk robot.launch.py`

**Comment by edugm94** [comment]
Hi @tfoldi ,

In the installation, it is mentioned: " For example, open3d does not yet support python3.12 and therefore you will need to set up a 3.11 venv first etc.". Can I run this project in a Conda environment? And if so, what are the requirements it should fulfill? 

Many thanks for considering my request.

**Comment by tfoldi** [comment]
what OS version and ROS version are you using? probably it might be easier to run this as a docker container

**Comment by Leonana69** [comment]
I got the same problem when I tried to run the sdk with conda environment. It's the problem of which python is used by ROS2. If you look at the `ros2_ws/install/go2_robot_sdk/lib/go2_robot_sdk/go2_driver_node`, you will see `#!/usr/bin/python3` which means ROS2 will use your system python by default. So you need to change it to your conda python like `/home/username/miniconda3/envs/go2/bin/python3`. I don't know if there is other solution but I just use this Makefile script to replace the python string.
```
.PHONY: build

build:
	colcon build
	@{ \
		PYTHON=$$(which python3 2>/dev/null || which python 2>/dev/null || echo "/usr/bin/python3"); \
		echo "Detected Python: $$PYTHON"; \
		find ./install -type f -executable -exec grep -l "^#!/usr/bin/python3" {} \; 2>/dev/null | while read -r file; do \
			if [ -f "$$file" ]; then \
				echo "Updating shebang in: $$file"; \
				sed -i '1s|^#!/usr/bin/python3|#!'"$$PYTHON"'|' "$$file"; \
				dos2unix "$$file" 2>/dev/null || sed -i 's/\r$$//' "$$file"; \
				chmod +x "$$file"; \
			fi; \
		done; \
	}
```
